### ISSUE TITLE
Image Generation - Number of Iterations

### ISSUE THREAD

**Issue by tibuch** [idiap/linear-transformer-experiments#1]
Hi,

Thank you for this example code on how to train the image generation example!

I just have one question regarding number of training iterations:
```
python main.py --dataset mnist --attention_type causal-linear \
    --d_query 32 --n_heads 8 --n_layers 8 --mixtures 10 \
    --batch_size 16 --iterations 937500 --evaluate_every 10000 \
    --save_to /path/to/weights.{}.pth \
    --continue_from /path/to/weights.{}.pth
```

Here the iteraions is set to 937500. Could it be that a 0 is missing and that the number of iterations should be 9375000? I am asking because of the save frequency which defaults to 3000. And 937500 is not divisible by 3000.

Thanks and best wishes!

**Comment by angeloskath** [comment]
Hi,

The save frequency is independent of the number of iterations total. It will just not save one model at the end. You could also set it to 939000 so it will be divisible but it makes little difference.

Cheers,
Angelos

**Comment by tibuch** [comment]
I understand. I trained the network now for 937500 iterations and evaluated on the 936000 weights. I compared the result to the results obtained with the linear-model-weights from [this](https://colab.research.google.com/drive/1BV4OaWRAHYGeimO0cqHD86GfnfgUaKD4?usp=sharing#scrollTo=-5to7CKVIfea) colab notebook.

Unfortunately our own training seems to look much worse :/
![image](https://user-images.githubusercontent.com/5450869/100836585-d5540680-346f-11eb-8bea-9d1351724ab2.png)

For this completion task the first `784//2` pixels of the mnist-number were provided.

**Comment by angeloskath** [comment]
Hm, this is unexpected. In my experiments the qualitative results are much better even significantly earlier in training.

How is the quantitative performance? What is the training and validation bpd?

Angelos

**Comment by tibuch** [comment]
It starts like this:
`Loss: 2.1336467266082764 bpd: 3.0782015514867305 lr: 0.0001 time: 0.01691339910030365`
First Testing:
`Testing => Loss: 1.1302731586456298 bpd: 1.6306394808279543`

A couple lines from the middle of the log file:
```
Loss: 1.0164016485214233 bpd: 1.4663576178732247 lr: 0.0001 time: 0.013946443796157837
Loss: 0.9447519183158875 bpd: 1.362988907424666 lr: 0.0001 time: 0.014082670211791992
Loss: 0.8934237360954285 bpd: 1.2889379934773646 lr: 0.0001 time: 0.014141499996185303
Loss: 0.9028260707855225 bpd: 1.3025026951075416 lr: 0.0001 time: 0.014116555452346802
Loss: 0.8675411939620972 bpd: 1.251597378296008 lr: 0.0001 time: 0.014118954539299011
```
Testing somewhere in the middle:
`Testing => Loss: 0.9537100784301757 bpd: 1.3759128005970391`

The last couple lines:
```
Loss: 0.8392305970191956 bpd: 1.2107538204818775 lr: 0.0001 time: 0.01389630138874054
Loss: 0.8903618454933167 bpd: 1.2845206190899534 lr: 0.0001 time: 0.014011427760124207
Loss: 0.9366657733917236 bpd: 1.3513230662426654 lr: 0.0001 time: 0.014120250940322876
Loss: 0.8886418342590332 bpd: 1.2820391674119793 lr: 0.0001 time: 0.014110788702964783
Loss: 0.9602646231651306 bpd: 1.3853690097814433 lr: 0.0001 time: 0.014075398445129395
Loss: 0.9272468686103821 bpd: 1.3377344590240186 lr: 0.0001 time: 0.014131873846054077
Loss: 0.8803771734237671 bpd: 1.2701157822103117 lr: 0.0001 time: 0.013904646039009094
Loss: 0.9522176384925842 bpd: 1.373759664900251 lr: 0.0001 time: 0.01401430368423462
```
Last testing:
`Testing => Loss: 0.9800876196861267 bpd: 1.4139675485578431`

**Comment by angeloskath** [comment]
Yep, from the log file I can see it practically doesn't learn anything. First evaluation 1.63 and last 1.4. It should be around 1.3 and <0.7 for sure.

I will run the script again to check if something has changed in the library that causes some instability or anything (unlikely) and let you know what I have found.

**Comment by angeloskath** [comment]
I will let it train but after only 10,000 iterations the training bpd is 1.1 which means it is already significantly better than your model at the end of training.

I just fetched `fast-transformers` from master built them and then ran the main.py as follows:

```
python main.py --dataset_directory /path/to/datasets/pytorch/ --dataset mnist --attention_type causal-linear \
    --d_query 32 --n_heads 8 --n_layers 8 --mixtures 10 --batch_size 16 \
    --save_to /path/to/output-dir/weights.{}.pth --continue_from /path/to/output-dir/weights.{}.pth \
    --iterations 937500 --save_frequency 13000 --yield_frequency 13000 --evaluate_frequency 13000
```

Let me know if you can think of anything you are doing differently.

Cheers,
Angelos

**Comment by tibuch** [comment]
You write 'built them'. I used `pip install --user pytorch-fast-transformers` to install the package. Do I have to build something else?

Thank you for looking into it!

**Comment by angeloskath** [comment]
pip install builds the extensions from source so it should be exactly the same.

**Comment by tibuch** [comment]
Ah maybe something went wrong during the install and I didn't pay attention. Is there a command which forces a rebuild?

**Comment by tibuch** [comment]
I also get this warning/error messages if I run the script:
```
/home/tbuchhol/Gitrepos/linear-transformer-experiments/image-generation/radam.py:93: UserWarning: This overload of addcmul_ is deprecated:
        addcmul_(Number value, Tensor tensor1, Tensor tensor2)
Consider using one of the following signatures instead:
        addcmul_(Tensor tensor1, Tensor tensor2, *, Number value) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  exp_avg_sq.mul_(beta2).addcmul_(1 - beta2, grad, grad)

```

**Comment by tibuch** [comment]
Okay I reinstalled the package and wanted to start the training. Now I am getting this:
```
  File "/home/tbuchhol/.local/lib/python3.7/site-packages/fast_transformers/attention/causal_linear_attention.py", l
ine 24, in causal_linear
    return V_new.permute(0,2,1,3).contiguous()
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped) 
```

nvidia-smi:
```
Wed Dec  2 15:18:42 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.118.02   Driver Version: 440.118.02   CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   34C    P0    49W / 250W |   1620MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     45411      C   .../Programs/miniconda3/envs/ft/bin/python   925MiB |
|    0     49791      C   .../Programs/miniconda3/envs/ft/bin/python   685MiB |
+-----------------------------------------------------------------------------+
```

cudatoolkit and pytorch:
```
conda list | grep cuda
cudatoolkit               10.2.89              hfd86e86_1  
pytorch                   1.7.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
```

But the system cuda is old:
`lrwxrwxrwx 1 root root 19 May 27  2019 /usr/local/cuda -> /usr/local/cuda-9.2/`
Maybe I have to upgrade this as well?

**Comment by tibuch** [comment]
Okay! That was the problem. Had to upgrade cuda to 10.2 and update the sym-link. 
Now I get this after 13'000:
`Testing => Loss: 0.7398167895317078 bpd: 1.0673300134237902`

Thanks for testing!
