### ISSUE TITLE
Training with causal-linear

### ISSUE THREAD

**Issue by pfabreu** [idiap/linear-transformer-experiments#2]
Thank you for this great implementation, very useful for replication purposes!

When trying to run 'causal-linear' attention or 'local' attention, or in general any attention that requires a CUDA compilation, I either get errors of the type:

```
TypeError: 'NoneType' object is not callable
```
in the CausalDotProduct.dot[device.type] CUDA code.
or my sec/sample is very high even on the GPU ([0.4349]).

EDIT: Fixed it, you 100% need CUDA 10.2 and cuDNN 8 and pytorch with CUDA 10.2. After you reinstall CUDA, reinstall pytorch-fast-transformer Works with Python 3.9 :)

**Comment by Mohan-Zhang-u** [comment]
Hi @pedro-abreu if possible, would you mind sharing the pytorch version that you were using? I tried pytorch 1.9.1 and 1.8.2 LTS with CUDA 10.2 and cuDNN 8 but the issue of 
`TypeError: 'NoneType' object is not callable`
still remains.[](url)

**Comment by pfabreu** [comment]
I honestly don't remember, but it was probably some variation of 1.8. If you install pytorch from pip you need to install it with the same CUDA version as you have on your machine (check it nvcc). That was basically the trick that did it.

**Comment by Mohan-Zhang-u** [comment]
> I honestly don't remember, but it was probably some variation of 1.8. If you install pytorch from pip you need to install it with the same CUDA version as you have on your machine (check it nvcc). That was basically the trick that did it.

Thanks a lot for your quick reply! I will give it a try.
