### ISSUE TITLE
Copy Task missing leading 0?

### ISSUE THREAD

**Issue by RobertCChen** [idiap/linear-transformer-experiments#3]
Thank you for the example code!

Am I missing something or is the copy task missing the leading 0?

i.e. in these lines:
```
x[:n] = random_sequence
x[n+1:2*n+1] = random_sequence
y[:-1] = x[1:]
```

`x` does not begin with 0, and thus `y` does not include the first random token.

**Comment by angeloskath** [comment]
Hi,

It is missing the leading 0 and y does indeed not include the first random token.

The task is as follows:

Given the sequence `(a, b, c, 0, a, b, c)` predict in autoregressive fashion the second half of the sequence. This means that the loss needs to be computed only for the tokens in the second half of the sequence. The pairs x, y and mask are generated as follows:

```
 x | y | m
---+---+---
 a | b | 0
 b | c | 0
 c | 0 | 0
 0 | a | 1
 a | b | 1
 b | c | 1
 c | 0 | 0
```

You can interpret the above as for each x you need to predict y only when m is 1.

Cheers,
Angelos

**Comment by RobertCChen** [comment]
I see, thanks for clarifying!
