### ISSUE TITLE
about the positional embeddings: why concatenation instead of addition?

### ISSUE THREAD

**Issue by Mohan-Zhang-u** [idiap/linear-transformer-experiments#6]
Thanks a lot for your great work and well-written papers!

I noticed that in your [fast transformers repo](https://github.com/idiap/fast-transformers/issues/5#issuecomment-654876848), you mentioned for ASR, you used fixed sinusoidal positional embeddings that are concatenated to the input. The concatenated features are then linearly projected and given as input to the transformer. which is the same as the PositionalEncoding class used in [causal-copy](https://github.com/idiap/linear-transformer-experiments/blob/master/causal-copy/main.py#L53) and [image-generation](https://github.com/idiap/linear-transformer-experiments/blob/master/image-generation/main.py#L25).

I'm wondering, in the causal-copy task for example, is there any particular reason why bother concatenate the positional embeddings, rather than directly add it to the value_embedding as the original transformer paper?

Thanks in advance for your time and reply!

**Comment by angeloskath** [comment]
Hi,

Thanks for your good words!

It makes little difference to either concatenate or add the positional embeddings so to simply answer your question, there is no particular reason whatsoever.

Cheers,
Angelos
